#!/bin/bash
#PBS -l walltime=01:00:00
#PBS -l ncpus=48
#PBS -q normal
#PBS -P w40
#PBS -l storage=gdata/hh5+gdata/w40+scratch/w40
#PBS -l mem=10gb
#PBS -N plot_vert_profiles

python /g/data/w40/dm5220/scripts/plot_analyses/plot_vertical_profiles.py  -i 4co2_solar50- 4co2_sw_x0.9452_offset -l 4co2_solar- 4co2_sw- -c darkorange firebrick -o 4co2_solar-.sw-
