#!/bin/bash
#PBS -l walltime=01:00:00
#PBS -l ncpus=48
#PBS -q normal
#PBS -P w48
#PBS -l storage=gdata/hh5+gdata/w48+scratch/w48
#PBS -l mem=10gb
#PBS -N plot_vert_profiles

python /g/data/w48/dm5220/scripts/plot_analyses/plot_vertical_profiles.py  -i test_-0.007 test_0.007 -l 4co2_sw-_tac-0.007 4co2_sw-_tac0.007 -o DIFF_test1_2 -C 4co2_sw_x0.9452_offset
