#!/bin/bash
#PBS -l walltime=10:00:00
#PBS -l ncpus=48
#PBS -q normal
#PBS -P w40
#PBS -l storage=gdata/hh5+gdata/w40+scratch/w40
#PBS -l mem=50gb
#PBS -N plot_anomal

python /g/data/w40/dm5220/scripts/plot_analyses/plot_anomalies.py  -i 4co2_fix_tsurf_best35 -o 4co2_fix_best35 -n
