#!/bin/bash
#PBS -l walltime=01:00:00
#PBS -l ncpus=48
#PBS -q normal
#PBS -P w40
#PBS -l storage=gdata/hh5+gdata/w40+scratch/w40
#PBS -l mem=190gb
#PBS -N um2nc.vaccl 

python3 /g/data3/w40/dm5220/scripts/um2nc/convert_um2nc.py --id vaccl --ncpus 48
