#!/bin/bash
#PBS -l walltime=01:00:00
#PBS -l ncpus=48
#PBS -q normal
#PBS -P w48
#PBS -l storage=gdata/hh5+gdata/w48+scratch/w48
#PBS -l mem=50gb
#PBS -N um2nc.ctl_fix_tsurf 

/g/data3/w48/dm5220/scripts/um2nc/convert_um2nc.py --id vacbc -o /g/data/w48/dm5220/data/ctl_fix_tsurf --ncpus 48
