#!/bin/bash
#PBS -l walltime=10:00:00
#PBS -l ncpus=4
#PBS -q normal
#PBS -P w48
#PBS -l storage=gdata/hh5+gdata/w48+scratch/w48+gdata/access
#PBS -l mem=150gb
#PBS -N create_tac_submit

python3 /g/data/w48/dm5220/scripts/tac_rad_change/create_tac.py

# /g/data/access/projects/access/apps/xancil/0.57/mkancil < /g/data/w48/dm5220/scripts/tac_rad_change/xancil.namelist_sw
# /g/data/access/projects/access/apps/xancil/0.57/mkancil < /g/data/w48/dm5220/scripts/tac_rad_change/xancil.namelist_solar
/g/data/access/projects/access/apps/xancil/0.57/mkancil < /g/data/w48/dm5220/scripts/tac_rad_change/xancil.namelist_test4
/g/data/access/projects/access/apps/xancil/0.57/mkancil < /g/data/w48/dm5220/scripts/tac_rad_change/xancil.namelist_test5
/g/data/access/projects/access/apps/xancil/0.57/mkancil < /g/data/w48/dm5220/scripts/tac_rad_change/xancil.namelist_test6