#!/bin/bash
#PBS -l walltime=10:00:00
#PBS -l ncpus=4
#PBS -q normal
#PBS -P w40
#PBS -l storage=gdata/hh5+gdata/w40+scratch/w40+gdata/access
#PBS -l mem=150gb
#PBS -N custom_tac_best13
#PBS -o /g/data3/w40/dm5220/scripts/tac_rad_change/custom_tac_best13.out
#PBS -e /g/data3/w40/dm5220/scripts/tac_rad_change/custom_tac_best13.err

python3 /g/data/w40/dm5220/scripts/tac_rad_change/create_custom_tac.py -b /g/data/w40/dm5220/ancil/user_mlevel/tac_rad_change/files_for_xancil/best4.nc --no-filter -c /scratch/w40/dm5220/tmp/tmp.8bhswkmWoZ -n best13 
rm /scratch/w40/dm5220/tmp/tmp.8bhswkmWoZ

/g/data/access/projects/access/apps/xancil/0.57/mkancil < "/g/data/w40/dm5220/scripts/tac_rad_change/xancil.namelist_best13"

