#!/bin/bash
#PBS -l walltime=10:00:00
#PBS -l ncpus=4
#PBS -q normal
#PBS -P w40
#PBS -l storage=gdata/hh5+gdata/w40+scratch/w40
#PBS -l mem=100gb
#PBS -N ch4_figs

python /g/data3/w40/dm5220/scripts/analysis/thesis_figures/sensitivity_experiments.py
