#!/bin/bash

change_line() {
    file=$1
    old_text=$2
    new_text=$3
    line=$(grep -n "$old_text" "$file" | cut -d: -f1 | head -1)
    sed -i ${line}"s|${old_text}.*|${new_text}|" "$file"
}

count=0
((count+=2))
jobID="sex${count}"
subID=000
refID="vabya"
dir="/home/565/dm5220/umui_runs"
refdir=$(find $dir -type d -name "$refID*" | tail -n 1)
UMoutdir="/scratch/$PROJECT/$USER/umui"
newoutdir="${UMoutdir}/tair_sex/${jobID}"
rm -rf ${dir}/sex[0-9]*
newdir="${dir}/${jobID}-${subID}"
mkdir "$newdir"
cp -r ${refdir}/* "$newdir"

# EDIT MULTILEVEL INPUT FILE
file="${newdir}/INITHIS"
change_line "$file" "USRMULTI=" "USRMULTI= 'USRMULTI : /g/data3/w48/dm5220/ancil/user_mlevel/tair_change/sex/sex${count}'"

# EDIT RUN SUBMIT FILE
file="${newdir}/umuisubmit_run"
# Change exp name in qstat
change_line "$file" "#PBS -N " "#PBS -N ${jobID}.run"
# Change log output dir
change_line "$file" "export UMRUN_OUTPUT=" "export UMRUN_OUTPUT=/home/565/dm5220/um_output/${jobID}000.${jobID}.d20363.t131134.leave"
# Change job name for log output dir
change_line "$file" "export CJOBN=" "export CJOBN=${jobID}000"
# Change file output dir
change_line "$file" "export JOBDIR=" "export JOBDIR=/home/565/dm5220/umui_runs/${jobID}-${subID}"
# Change submission id
change_line "$file" "export SUBMITID=" "export SUBMITID=${subID}"
# Change output dir
change_line "$file" "UM_DATAW=" "UM_DATAW=${newoutdir}"
change_line "$file" "UM_DATAM=" "UM_DATAM=${newoutdir}"
# Change run to 1yr for test
change_line "$file" "export RESUB_INC_YEARS=" "export RESUB_INC_YEARS=1"

# Make output directory and copy compilation files in it
mkdir -p "$newoutdir"
cp -r "$UMoutdir/$refID/bin" "$newoutdir"

# qsub "$file"




# # EDIT COMPILATION SUBMIT FILE
# file="${newdir}/umuisubmit_clr"
# # Change log output name
# change_line "$file" "#PBS -o " "#PBS -o /home/565/dm5220/um_output/${jobID}${subID}.${jobID}.d21008.t173330.comp.leave"
# # Change exp name in qstat
# change_line "$file" "#PBS -N " "#PBS -N ${jobID}.compile"
# # Change output dir
# change_line "$file" "export UM_RDATADIR=" "export UM_RDATADIR=/scratch/$PROJECT/$USER/umui/tair_sex/${jobID}"
# # Change umuisubmit file dir
# change_line "$file" "qsub -S /bin/ksh " "qsub -S /bin/ksh ${newdir}/umuisubmit_run"

# # EDIT COMPILATION SUBMIT FILE
# file="${newdir}/umuisubmit_compile"
# # Change log output name
# change_line "$file" "#PBS -o " "#PBS -o /home/565/dm5220/um_output/${jobID}${subID}.${jobID}.d21008.t173330.comp.leave"
# # Change exp name in qstat
# change_line "$file" "#PBS -N " "#PBS -N ${jobID}.compile"
# # Change output dir
# change_line "$file" "export UM_RDATADIR=" "export UM_RDATADIR=/scratch/$PROJECT/$USER/umui/tair_sex/${jobID}"

