#!/bin/bash
#PBS -l walltime=10:00:00
#PBS -l ncpus=1
#PBS -q normal
#PBS -P w48
#PBS -l storage=gdata/hh5+gdata/w48+scratch/w48+gdata/access
#PBS -l mem=50gb

/g/data3/w48/dm5220/scripts/tair_change/mlevel_tair_correction.py -o test -c 0.2 -s3 0.5 -s1 0.3 -s4 0.8 -s12 -0.3
/g/data/access/projects/access/apps/xancil/0.57/mkancil < "/g/data3/w48/dm5220/scripts/tair_change/xancil.namelist_mlevel_tair_change"
/g/data/w48/dm5220/scripts/util/fix_polar_anom "/g/data/w48/dm5220/ancil/user_mlevel/tair_change/test" #fix polar errors
