#!/bin/bash
#PBS -l walltime=10:00:00
#PBS -l ncpus=4
#PBS -q normal
#PBS -P w40
#PBS -l storage=gdata/hh5+gdata/w40+scratch/w40+gdata/access
#PBS -l mem=50gb

/g/data/access/projects/access/apps/xancil/0.57/mkancil < "/g/data3/w40/dm5220/scripts/tair_change/xancil.namelist_slevel"
