#!/bin/bash
#PBS -l walltime=10:00:00
#PBS -l ncpus=4
#PBS -q normal
#PBS -P w48
#PBS -l storage=gdata/hh5+gdata/w48+scratch/w48+gdata/access
#PBS -l mem=50gb

echo "Writing Sea Surface Temperature netCDF file: /g/data/w48/dm5220/ancil/sst/prescribed/files_for_xancil/tac_ctl.nc"
/g/data3/w48/dm5220/scripts/prescribed_tsurf/monthly_sst.py -i /g/data/w48/dm5220/data/tac_control -o /g/data/w48/dm5220/ancil/sst/prescribed/files_for_xancil/tac_ctl.nc
/g/data/access/projects/access/apps/xancil/0.57/mkancil < "/g/data3/w48/dm5220/scripts/prescribed_tsurf/xancil.namelist_monthly_sst"
