#!/bin/bash
#PBS -l walltime=00:30:00
#PBS -l ncpus=48
#PBS -q normal
#PBS -P w48
#PBS -l storage=gdata/hh5+gdata/w48+scratch/w48
#PBS -l mem=50gb
#PBS -N test 

python /g/data3/w48/dm5220/scripts/analysis/test.py

