#!/bin/bash
#PBS -l walltime=00:30:00
#PBS -l ncpus=48
#PBS -q normal
#PBS -P w40
#PBS -l storage=gdata/hh5+gdata/w40+scratch/w40
#PBS -l mem=50gb
#PBS -N test 

python /g/data3/w40/dm5220/scripts/analysis/test.py

