#!/bin/bash
#PBS -l walltime=01:00:00
#PBS -l ncpus=48
#PBS -q normal
#PBS -P w48
#PBS -l storage=gdata/hh5+gdata/w48+scratch/w48
#PBS -l mem=10gb
#PBS -N plot_vert_profiles

python /g/data/w48/dm5220/scripts/analysis/plot_vertical_profiles.py  -i vacca vaccb vaccc
