#!/bin/bash
#PBS -l walltime=01:00:00
#PBS -l ncpus=48
#PBS -q normal
#PBS -P w40
#PBS -l storage=gdata/hh5+gdata/w40+scratch/w40
#PBS -l mem=10gb
#PBS -N plot_anomal

python /g/data/w40/dm5220/scripts/analysis/plot_anomalies.py  -i vaccc
